name: ci

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build Multi-Architecture Image
        if: github.ref != 'refs/heads/master'
        run: make docker-buildx
